name: Tests

on:
  workflow_call:
    inputs:
      docker:
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] 
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - if: ${{ inputs.docker }}
        run: ${{ inputs.docker }}
      - run: cargo test --all-features
