name: Tests

on:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=https://github.com/nixos/nixpkgs/archive/nixpkgs-unstable.tar.gz
          enable_kvm: true
      - uses: cachix/cachix-action@v15
        with:
          name: soywod
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - run: nix-shell --run "cargo test --all-features"
